services:
  db:
    image: postgres:15-alpine
    container_name: auctions_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: Auctions_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db